version: '2'
services:

  datadevselenium:
    extends:
      file: docker-compose-common.yml
      service: datadevselenium

  dataprodselenium:
    extends:
      file: docker-compose-common.yml
      service: dataprodselenium

  # runs the aloe tests against docker-compose-teststack.yml
  teststack:
    image: muccg/mastrms-dev
    command: lettuce
    environment:
      - WAIT_FOR_RUNSERVER=1
      - WAIT_FOR_DB=1
      - TEST_WAIT=10
      - TEST_BROWSER=chrome
      - DEBUG=0
      - RUNSERVER=runservertest
      - DBSERVER=dbtest
      - CACHESERVER=cachetest
    volumes_from:
      - datadevselenium

  # runs the aloe tests against docker-compose-prod.yml
  prod:
    image: muccg/mastrms-dev
    command: lettuce
    environment:
      - WAIT_FOR_UWSGI=1
      - WAIT_FOR_DB=1
      - TEST_APP_HOST=nginxtest
      - TEST_APP_PORT=443
      - TEST_APP_SCHEME=https
      - TEST_APP_PATH=/app/
      - TEST_WAIT=10
      - TEST_BROWSER=chrome
      - DEBUG=0
      - RUNSERVER=runservertest
      - DBSERVER=dbtest
      - CACHESERVER=cachetest
      - UWSGISERVER=uwsgitest
    volumes_from:
      - dataprodselenium
